version: "3"
services: 
  mongo:
    container_name: mongo-container 
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api_container
    build: .
    image: clean-node-api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/dist/package.json
    ports: 
      - "7777:7777"
      - "9222:9222"
    links: 
      - mongo